###### Motion controlling interface

### Action Service Goal

# the plan as a set of points to reach
Point[] via_points

---

### Action Server Result

# the reached point
Point reached_point

---

### Action Server Feedback

# the last via_points reached
Point reached_point